name: video_downloader_assistant
description: A Flutter app to download Douyin/Xiaohongshu videos.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.3
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  clipboard: ^0.1.3

flutter:
  uses-material-design: true
